# Generated by Django 4.2.16 on 2024-11-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='covertype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
