# Generated by Django 4.2.16 on 2024-12-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
